GET http://localhost:8080/app

###

POST http://localhost:8080/api/validate_chirp
Content-Type: application/json

{
    "body": "This is an opinion I kerfuffle need to share with the world"
}

###

POST http://localhost:8080/admin/reset

###

POST http://localhost:8080/api/users
Content-Type: application/json

{
    "email": "user@example.com"
}

###

POST http://localhost:8080/api/chirps
Content-Type: application/json

{
  "body": "Hello, world!",
  "user_id": "ce68b6d0-1433-46cd-84d1-16a7db76b4cb"
}

###

GET http://localhost:8080/api/chirps